[project]
name = "w1"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.3.3",
    "pandas-stubs==2.3.3.251219",
    "pyarrow>=22.0.0",
]

[dependency-groups]
dev = [
    "pgcli>=4.4.0",
]
